### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by afanmatvey** [devnull-tools/build-notifications-plugin#2]
Why can not be installed in the usual way?

**Comment by ataxexe** [comment]
Actually I've not uploaded it to the Jenkins plugin repository. My bad!

I'll work on that.

**Comment by unreal4u** [comment]
Any updates on this? It would be nice to have Telegram notifications but if it can't be installed through the plugin manager we can't use it :( (Company policies).

**Comment by fgimenez** [comment]
+1

**Comment by ataxexe** [comment]
I've filed a request here: https://issues.jenkins-ci.org/browse/HOSTING-69

**Comment by ataxexe** [comment]
Sorry for the huge delay. I'm working on prepare things for continuing with the hosting request. The first thing is to rename the project on GitHub to reflect Jenkins' policies and then I need to fix the `getRequiredMonitorService` method.

**Comment by ataxexe** [comment]
I'm checking with them if I really need to rename the project.

**Comment by ataxexe** [comment]
Issues solved, I'll postpone #13 because is a correct behavior (but needs to be improved in some scenarios) but it doesn't affect the hosting.

**Comment by ataxexe** [comment]
Almost done:

https://github.com/jenkinsci/build-notifications-plugin

Now I'm going to set up things and upload one release to the repository. Will update this as soon as it's done.

Thank you guys!!

**Comment by unreal4u** [comment]
On the contrary, thank you for doing this!

**Comment by ataxexe** [comment]
I'm releasing the 1.4.2 version (yes, I'm dumb enough to miss some things in order to use the maven release plugin and the new dogma-styled findbugs stuff, but I promise you I've learned enough to maintain my sanity and the plugin quality).

Again, thank you so much for pushing me towards a more wide collaboration to the community. It's great to see something I made useful to others.
